---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podrefresh
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podrefresh
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podrefresh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podrefresh
subjects:
- kind: ServiceAccount
  name: podrefresh
  namespace: kube-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: podrefresh
  namespace: kube-system
spec:
  schedule: "0 0 * * *"  # Run at midnight every day
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: podrefresh
        spec:
          serviceAccountName: podrefresh
          restartPolicy: OnFailure
          containers:
          - name: podrefresh
            image: ghcr.io/abihf/podrefresh:latest
            imagePullPolicy: Always
            resources:
              requests:
                memory: "32Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "200m"
